const quotesActionTypes = {
	FETCH_QUOTES_START: 'FETCH_QUOTES_START',
	FETCH_QUOTES_SUCCESS: 'FETCH_QUOTES_SUCCESS',
	FETCH_QUOTES_FAULURE: 'FETCH_QUOTES_FAILURE',
	SET_MY_QUOTES: 'SET_MY_QUOTES',
	ADD_QUOTE: 'ADD_QUOTE',
	DELETE_QUOTE_SUCCESS: 'DELETE_QUOTE_SUCCESS',
	CLEAR_QUOTES: 'CLEAR_QUOTES',
	FIND_IT: 'FIND_IT'
};

export default quotesActionTypes;
